name: Build Flet APK
on: 
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/android'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          pip install flet
          flet build apk
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pdf-lite-v102-apk
          path: build/apk/*.apk
